name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1    
    - name: Build and export
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        #builder: docker build
        #push: true
        tags: dockertest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        outputs: type=docker,dest=/tmp/myimage.tar
    - name: Load and Run docker
      run: |
        docker load --input /tmp/myimage.tar
        docker run -di -P --rm --privileged -v ${GITHUB_WORKSPACE}/tmp/html_coverage/:/canfault/coverage_html_report/ dockertest
        dir
        cd tmp
        dir
        cd html_coverage
        dir
        pwd
        sudo echo 'testing artifacts' >> test.txt
        ls
     # docker load --input /tmp/myimage.tar
    #- name: Run the Docker image
    #  run: docker run --privileged --rm -i dockertest && ls canfault
    # uploading files to artifact, /home/runner/work/DVGC23/DVGC23/tmp/html_coverage alt ${GITHUB_WORKSPACE}/tmp/html_coverage/
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: html_coverage
        path: /home/runner/work/DVGC23/DVGC23/tmp/html_coverage/index.html
   # - name: Build the Docker image
   #   run: docker build . --file Dockerfile --tag dockertest
