name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1    
    - name: Build and export
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        tags: dockertest
        push: false
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        outputs: type=docker,dest=/tmp/myimage.tar
    - name: Run docker
      uses: addnab/docker-run-action@v3
      with:
        image: /tmp/myimage.tar
        options: -di -P --rm --privileged -v ${GITHUB_WORKSPACE}/tmp/:/canfault/:rw dockertest
    # uploading files to artifact, /home/runner/work/DVGC23/DVGC23/tmp/html_coverage alt ${GITHUB_WORKSPACE}/tmp/html_coverage/
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: html_coverage
        path: tmp/canfault/coverage_html_report/
